# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      MAVEN_REPO_PATH: "/home/runner/m2/repository"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven environment
        run: echo "MAVEN_REPO=${MAVEN_REPO_PATH}" >> $GITHUB_ENV

      - name: Configure Maven
        run: |
          mkdir -p /home/runner/m2/repository
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
            xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
            xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <localRepository>/home/runner/m2/repository</localRepository>
          </settings>" > /home/runner/m2/settings.xml

      #- name: Install with Maven
      #  run: mvn clean -DskipTests source:jar install

      #- name: Deploy with Maven
      #  run: mvn clean -DskipTests source:jar deploy

      - name: Test with Maven
        run: mvn test

      #- name: Build with Maven
      #  run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
